### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by joshgarnett** [splunk/docker-splunk-legacy#4]
The splunk container process exits immediately when running the steps specified in the README.  I'm seeing the issue with 6.3.3 and 6.3.1.  Below are the logs

```
$ docker logs splunk
Copying '/opt/splunk/etc/openldap/ldap.conf.default' to '/opt/splunk/etc/openldap/ldap.conf'.
Generating RSA private key, 1024 bit long modulus
.......................................++++++
............++++++
e is 65537 (0x10001)
writing RSA key

Generating RSA private key, 1024 bit long modulus
...................++++++
.........++++++
e is 65537 (0x10001)
writing RSA key

Moving '/opt/splunk/share/splunk/search_mrsparkle/modules.new' to '/opt/splunk/share/splunk/search_mrsparkle/modules'.

An unforeseen error occurred:

    Exception: <type 'exceptions.OSError'>, Value: [Errno 39] Directory not empty: '/opt/splunk/share/splunk/search_mrsparkle/modules.new/converters'

Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli.py", line 1150, in main
    parseAndRun(argsList)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli.py", line 997, in parseAndRun
    retVal = cList.getCmd(command, subCmd).call(argList, fromCLI = True)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli.py", line 280, in call
    return self.func(args, fromCLI)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/control_api.py", line 30, in wrapperFunc
    return func(dictCopy, fromCLI)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/_internal.py", line 160, in firstTimeRun
    comm.moveItem(migration.PATH_UI_MOD_NEW, migration.PATH_UI_MOD_ACTIVE)
  File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli_common.py", line 856, in moveItem
    shutil.move(src, dst)
  File "/opt/splunk/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/opt/splunk/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/opt/splunk/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/opt/splunk/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/opt/splunk/share/splunk/search_mrsparkle/modules.new/converters'


Please file a case online at http://www.splunk.com/page/submit_issue


This appears to be your first time running this version of Splunk.
```

**Comment by joshgarnett** [comment]
Inside the container:

```
root@f1fb2a5ccfaf:/opt/splunk/share/splunk/search_mrsparkle/modules.new/converters# ls -la
ls: cannot access ConvertToDrilldownSearch.conf: No such file or directory
ls: cannot access ConvertToDrilldownSearch.js: No such file or directory
ls: cannot access ConvertToIntention.conf: No such file or directory
ls: cannot access ConvertToIntention.js: No such file or directory
ls: cannot access ConvertToRedirect.conf: No such file or directory
ls: cannot access ConvertToRedirect.js: No such file or directory
total 8
drwxr-xr-x 1 splunk splunk 4096 Mar  9 00:09 .
drwxr-xr-x 1 splunk splunk 4096 Mar  9 00:09 ..
?????????? ? ?      ?         ?            ? ConvertToDrilldownSearch.conf
?????????? ? ?      ?         ?            ? ConvertToDrilldownSearch.js
?????????? ? ?      ?         ?            ? ConvertToIntention.conf
?????????? ? ?      ?         ?            ? ConvertToIntention.js
?????????? ? ?      ?         ?            ? ConvertToRedirect.conf
?????????? ? ?      ?         ?            ? ConvertToRedirect.js
```

```
$ docker info
Containers: 37
Images: 293
Server Version: 1.10.1
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-2.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.461 GiB
ID: LQFZ:ZD3Q:M6PY:BNII:2PPW:NLDF:YCUN:5M52:KTJP:3JEB:K7ZJ:UKEM
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by joshgarnett** [comment]
I wonder if there might be issues with the overlay driver

**Comment by joshgarnett** [comment]
Yeah looks like that is the case, I'll debug this on my end.  Sorry for the noise.

**Comment by tanyewei** [comment]
@joshgarnett how to fix it?

**Comment by joshgarnett** [comment]
The issue was related to attempting to run the container in a CentOS 7 Vagrant instance with the overlay driver.  The overlay driver does not play well with `Backing Filesystem: xfs`.  I just switched to the default devicemapper driver.

**Comment by pikeszfish** [comment]
How can I fix it without switching to the default devicemapper driver?

**Comment by greenpau** [comment]
In case someone might need it.

> How to switch to `devicemapper` storage driver from `overlay` (XFS)?

On CentOS/RHEL, modify the `--storage-driver=overlay` to `--storage-driver=devicemapper` in `/etc/systemd/system/docker.service.d/override.conf`.
