### ISSUE TITLE
 [Errno 39] Directory not empty: '/opt/splunk/share/splunk/search_mrsparkle/modules.new/converters'

### ISSUE THREAD

**Issue by kamal2222ahmed** [splunk/docker-splunk-legacy#60]
Error installing with docker-compose up

git clone https://github.com/splunk/docker-splunk.git
Cloning into 'docker-splunk'...
remote: Counting objects: 817, done.
remote: Total 817 (delta 0), reused 0 (delta 0), pack-reused 817
Receiving objects: 100% (817/817), 156.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (393/393), done.
[ec2-user@ip-10-193-206-13 SPLUNK]$ ls
docker-splunk
[ec2-user@ip-10-193-206-13 SPLUNK]$ cd docker-splunk/
[ec2-user@ip-10-193-206-13 docker-splunk]$ ls
CONTRIBUTING.md  enterprise  LICENSE  README.md  universalforwarder
[ec2-user@ip-10-193-206-13 docker-splunk]$ cd enterprise/
[ec2-user@ip-10-193-206-13 enterprise]$ ls
build.sh  docker-compose.yml  Dockerfile  entrypoint.sh  publishImage.sh  README.md
[ec2-user@ip-10-193-206-13 enterprise]$ vim docker-compose.yml
[ec2-user@ip-10-193-206-13 enterprise]$ docker-compose up
Creating network "enterprise_default" with the default driver
Creating volume "enterprise_opt-splunk-etc" with default driver
Creating volume "enterprise_opt-splunk-var" with default driver
Pulling splunkenterprise (splunk/splunk:7.0.0)...
7.0.0: Pulling from splunk/splunk
Digest: sha256:216f8511d99b7e79ac147cf49829b92ad49a92ec8de35baf5beaf1bb50d9316c
Status: Downloaded newer image for splunk/splunk:7.0.0
Creating enterprise_splunkenterprise_1 ...
Creating enterprise_splunkenterprise_1 ... done
Attaching to enterprise_splunkenterprise_1
splunkenterprise_1  | Copying '/opt/splunk/etc/openldap/ldap.conf.default' to '/opt/splunk/etc/openldap/ldap.conf'.
splunkenterprise_1  | Generating RSA private key, 2048 bit long modulus
splunkenterprise_1  | .........................+++
splunkenterprise_1  | .......................+++
splunkenterprise_1  | e is 65537 (0x10001)
splunkenterprise_1  | writing RSA key
splunkenterprise_1  |
splunkenterprise_1  | Generating RSA private key, 2048 bit long modulus
splunkenterprise_1  | .....................................................+++
splunkenterprise_1  | .....................+++
splunkenterprise_1  | e is 65537 (0x10001)
splunkenterprise_1  | writing RSA key
splunkenterprise_1  |
splunkenterprise_1  | Moving '/opt/splunk/share/splunk/search_mrsparkle/modules.new' to '/opt/splunk/share/splunk/search_mrsparkle/modules'.
splunkenterprise_1  |
splunkenterprise_1  | An unforeseen error occurred:
splunkenterprise_1  |
splunkenterprise_1  |   Exception: <type 'exceptions.OSError'>, Value: [Errno 39] Directory not empty: '/opt/splunk/share/splunk/search_mrsparkle/modules.new/converters'
splunkenterprise_1  |
splunkenterprise_1  | Traceback (most recent call last):
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli.py", line 1143, in main
splunkenterprise_1  |     parseAndRun(argsList)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli.py", line 998, in parseAndRun
splunkenterprise_1  |     retVal = cList.getCmd(command, subCmd).call(argList, fromCLI = True)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli.py", line 280, in call
splunkenterprise_1  |     return self.func(args, fromCLI)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/control_api.py", line 30, in wrapperFunc
splunkenterprise_1  |     return func(dictCopy, fromCLI)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/_internal.py", line 176, in firstTimeRun
splunkenterprise_1  |     comm.moveItem(migration.PATH_UI_MOD_NEW, migration.PATH_UI_MOD_ACTIVE)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/site-packages/splunk/clilib/cli_common.py", line 1017, in moveItem
splunkenterprise_1  |     shutil.move(src, dst)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/shutil.py", line 300, in move
splunkenterprise_1  |     rmtree(src)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/shutil.py", line 247, in rmtree
splunkenterprise_1  |     rmtree(fullname, ignore_errors, onerror)
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/shutil.py", line 256, in rmtree
splunkenterprise_1  |     onerror(os.rmdir, path, sys.exc_info())
splunkenterprise_1  |   File "/opt/splunk/lib/python2.7/shutil.py", line 254, in rmtree
splunkenterprise_1  |     os.rmdir(path)
splunkenterprise_1  | OSError: [Errno 39] Directory not empty: '/opt/splunk/share/splunk/search_mrsparkle/modules.new/converters'
splunkenterprise_1  |
splunkenterprise_1  |
splunkenterprise_1  | Please file a case online at http://www.splunk.com/page/submit_issue
splunkenterprise_1  |
splunkenterprise_1  |
splunkenterprise_1  | This appears to be your first time running this version of Splunk.
enterprise_splunkenterprise_1 exited with code 2
[ec2-user@ip-10-193-206-13 enterprise]$

**Comment by david-crowder** [comment]
What storage driver are you using? I get the same error when I try and build on a system that is set to overlay but doesn't have `ftype=1` set:
https://docs.docker.com/storage/storagedriver/overlayfs-driver/#prerequisites

**Comment by hexecute** [comment]
I experienced this issue with Docker using the Overlay2 storage driver. Switching to Devicemapper fixed it for me.

**Comment by robdobtob** [comment]
Based on this issue and adding the splunk_share volume, was able to resolve the issue
`- splunk_share:/opt/splunk/share/splunk/search_mrsparkle/modules`

https://github.com/splunk/docker-splunk-legacy/issues/59
